package app.chat.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorEnum {


    //TODO NOT FOUND
    USER_NOT_FOUND(10),
    CHANNEL_NOT_FOUND(20),
    GROUP_NOT_FOUND(30),
    CHAT_NOT_FOUND(40),
    USERNAME_NOT_FOUND(50),
    SETTINGS_NOT_FOUND(60),
    PERSONAL_NOT_FOUND(70),
    MESSAGE_NOT_FOUND(80),
    FILE_NOT_FOUND(90),
    ERROR_NOT_FOUND(100),
    YOU_NOT_MEMBER_IN_CHANNEL(21),
    PERSONAL_MESSAGE_NOT_FOUND(61),
    USER_GROUP_NOT_FOUND(62),
    CHANNEl_MESSAGE_NOT_FOUND(63),
    CHANNEL_USER_NOT_FOUND(24),
    CHAT_ROLE_NOT_FOUND(110),
    USER_CONTACT_NOT_FOUND(120),

    //TODO ALREADY EXIST
    USERNAME_ALREADY_EXIST(51),
    EMAIL_ALREADY_EXIST(11),
    MEMBER_ALREADY_EXIST(13),

    //TODO CANT
    INVALID_EMAIL(12),
    PERSONAL_CANT_CREATE(71),
    USER_CONFLICT(121),


    //TODO BAD REQUEST
    LARGE_DESCRIPTION(41),
    LIMIT_MEMBER_REACHED(22),
    YOU_NOT_MEMBER_IN_GROUP(32),
    NO_PERMISSION(101),
    CANT_VIEW(81),

    //TODO BLOCKED
    USER_BLOCKED_IN_CHANNEL(23),
    USER_BLOCKED_IN_GROUP(33),
    YOU_BLOCKED_THIS_USER(14),
    THIS_USER_BLOCKED_YOU(15),

    ;
    private final Integer code;

}
